"""adding date added to users table

Revision ID: 6b7624952abe
Revises: 9256a73278f2
Create Date: 2022-07-28 12:39:31.133581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7624952abe'
down_revision = '9256a73278f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_added', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_added')
    # ### end Alembic commands ###
