"""Removing staff_type

Revision ID: 8a88909c259d
Revises: 
Create Date: 2022-07-28 07:51:37.142638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a88909c259d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'staff_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('staff_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
