"""making team leader db.String

Revision ID: 9256a73278f2
Revises: 945aa8b058d7
Create Date: 2022-07-28 08:38:02.012999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9256a73278f2'
down_revision = '945aa8b058d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adhaactsrating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starting_date_time', sa.String(), nullable=True),
    sa.Column('finishing_date_time', sa.String(), nullable=True),
    sa.Column('gps_location', sa.String(), nullable=True),
    sa.Column('governorate', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('its_name', sa.String(), nullable=True),
    sa.Column('p_code', sa.String(), nullable=True),
    sa.Column('nb_of_families', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('if_other_type', sa.String(), nullable=True),
    sa.Column('donor', sa.String(), nullable=True),
    sa.Column('team_leader', sa.String(), nullable=True),
    sa.Column('targeted_nb_in_camp', sa.Integer(), nullable=True),
    sa.Column('distributed_items', sa.Integer(), nullable=True),
    sa.Column('nb_of_itmes_to_be_distributed_in_this_act', sa.Integer(), nullable=True),
    sa.Column('exists_of_written_scheduled', sa.Integer(), nullable=True),
    sa.Column('voucher_distributed', sa.Integer(), nullable=True),
    sa.Column('beneficiaries_list_ready_used', sa.Integer(), nullable=True),
    sa.Column('protect_policies_respect_rate', sa.Integer(), nullable=True),
    sa.Column('controllcing_workplacce_rate', sa.Integer(), nullable=True),
    sa.Column('commitment_to_Covid_precautions', sa.Integer(), nullable=True),
    sa.Column('existing_of_requicrements', sa.Integer(), nullable=True),
    sa.Column('if_shortcoming_in_requirements', sa.String(), nullable=True),
    sa.Column('randomly_checked_item_rate', sa.Integer(), nullable=True),
    sa.Column('staff_performance', sa.Integer(), nullable=True),
    sa.Column('general_notes', sa.String(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('AdhaActivitiesRating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdhaActivitiesRating',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"AdhaActivitiesRating_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('starting_date_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('finishing_date_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gps_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('governorate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('its_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('p_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nb_of_families', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('if_other_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('donor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team_leader', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('targeted_nb_in_camp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distributed_items', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nb_of_itmes_to_be_distributed_in_this_act', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exists_of_written_scheduled', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('voucher_distributed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('beneficiaries_list_ready_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('protect_policies_respect_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('controllcing_workplacce_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('commitment_to_Covid_precautions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('existing_of_requicrements', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('if_shortcoming_in_requirements', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('randomly_checked_item_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('staff_performance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('general_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='AdhaActivitiesRating_pkey')
    )
    op.drop_table('adhaactsrating')
    # ### end Alembic commands ###
