"""adding added by column

Revision ID: 945aa8b058d7
Revises: 8a88909c259d
Create Date: 2022-07-28 08:07:28.321548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945aa8b058d7'
down_revision = '8a88909c259d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AdhaActivitiesRating', sa.Column('added_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AdhaActivitiesRating', 'added_by')
    # ### end Alembic commands ###
