"""adding date added edited to aar table

Revision ID: a22c2cdb8403
Revises: decf33b9ae82
Create Date: 2022-07-31 10:28:50.488044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22c2cdb8403'
down_revision = 'decf33b9ae82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adhaactsrating', sa.Column('date_added', sa.String(), nullable=True))
    op.add_column('adhaactsrating', sa.Column('date_edited', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adhaactsrating', 'date_edited')
    op.drop_column('adhaactsrating', 'date_added')
    # ### end Alembic commands ###
