"""fixing 5ata2 2emla2

Revision ID: b3b1b659acd7
Revises: a22c2cdb8403
Create Date: 2022-07-31 12:40:11.744791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b1b659acd7'
down_revision = 'a22c2cdb8403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adhaactsrating', sa.Column('existing_of_requirements', sa.Integer(), nullable=True))
    op.drop_column('adhaactsrating', 'existing_of_requicrements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adhaactsrating', sa.Column('existing_of_requicrements', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('adhaactsrating', 'existing_of_requirements')
    # ### end Alembic commands ###
