"""adding date edited to users table

Revision ID: decf33b9ae82
Revises: 6b7624952abe
Create Date: 2022-07-31 06:30:16.823440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decf33b9ae82'
down_revision = '6b7624952abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_edited', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_edited')
    # ### end Alembic commands ###
